### ISSUE TITLE
Pear issue

### ISSUE THREAD

**Issue by ben-leonard** [jamiesykescreode/cdev-environment-local#11]
When I run:

```
cdev env:start
```

The pear dependancy appears to be attempting to locate a file that doesn't exist. See following command line output.

```
Warning: require_once(PEAR.php): failed to open stream: No such file or directory in /Users/benleonard/.cdev/plugins/vendor/pear/config/Config.php on line 20
```

I have temporary resolved this issue locally by adding PEAR.php to /Users/benleonard/.cdev/plugins/vendor/pear/config/ after downloading it from here: https://pear.php.net/package/PEAR/download/

**Comment by jamiesykescreode** [comment]
When you get in let's take a look into this.

Thanks

**Comment by jamiesykescreode** [comment]
Issue was a dependency problem and has been resolved in later updates.
