### ISSUE TITLE
Database files not imported

### ISSUE THREAD

**Issue by garethmidwood** [jamiesykescreode/cdev-environment-local#16]
Standard cdev process is to import the DB files in the `db` folder (sibling of `cdev` and `src`) when the environment is started.

At the moment this isn't happening and you have to import them manually.

**Comment by jamiesykescreode** [comment]
Did we come a conclusion on this.

**Comment by jamiesykescreode** [comment]
using the backup directory rather than /db.

Need to remove the code to do this and just hardcode the db.

**Comment by garethmidwood** [comment]
Submitted a PR to address this - https://github.com/jamiesykescreode/cdev-environment-local/pull/20

**Comment by jamiesykescreode** [comment]
👍
