### ISSUE TITLE
Apache - log file per site

### ISSUE THREAD

**Issue by garethmidwood** [jamiesykescreode/cdev-environment-local#22]
It would be good to separate the log files for each site, currently they all go to the default log location.

When installing cdev local you're asked for a default docroot, is it possible to create a `logs` directory in here and separate project directories - perhaps using the domain name as the dir name

**Comment by garethmidwood** [comment]
Addressed in https://github.com/jamiesykescreode/cdev-environment-local/pull/23

**Comment by jamiesykescreode** [comment]
Looks fine, merged in.
