### ISSUE TITLE
Installation error - pear/config not found

### ISSUE THREAD

**Issue by garethmidwood** [jamiesykescreode/cdev-environment-local#7]
When installing the plugin I get an error

```
$ cdev plugin:install cdev/environment-local
>>> Running `php /usr/local/bin/composer.phar require cdev/environment-local`
Using version ^1.0@beta for cdev/environment-local
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for cdev/environment-local ^1.0@beta -> satisfiable by cdev/environment-local[1.0.0-beta1].
    - cdev/environment-local 1.0.0-beta1 requires pear/config dev-trunk -> no matching package found.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.
```

I *think* it's because `pear/config` doesn't exist, at least I can't find it on packagist.org...

**Comment by jamiesykescreode** [comment]
Pushed a potential fix to this into the 1.x branch. Will be tested and fixed as part of the next release.

**Comment by jamiesykescreode** [comment]
mm this might not be the case that it was fixed will try a few things.

**Comment by jamiesykescreode** [comment]
Tried the replicate the above locally after pushing a "potential fix" could you please double check this @garethmidwood ?

**Comment by jamiesykescreode** [comment]
@garethmidwood Just tried installing on Michal's machine. The reason we is isn't working is because of this: https://getcomposer.org/doc/faqs/why-can%27t-composer-load-repositories-recursively.md

Here we have 3 options:

* Either I rewrite my plugin to not use the Pear Config package and try to find an alternative.
* We add the repository VCS line to cdev core.
* We add the creode packagist in and add a fork of pear/Config to it.

Curious to get your input.

Cheers.

**Comment by jamiesykescreode** [comment]
What if I add a command to cdev core that will wrap the ```composer config repositories.repo-name vcs https://github.com/<orgname or username>/repo```

A specific command can then be added as part of the local environment plugin setup.

**Comment by garethmidwood** [comment]
How about we fork pear/Config and add that fork to packagist?

**Comment by jamiesykescreode** [comment]
As we don't currently know the licensing for Pear the safest option here is to add a new command into Cdev Core which allows you to add a new repository to your cdev composer file.

I'll open a new issue on Cdev core and work on this when I have time.
